######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 20 14:13:46 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += calc.cpp
